services:
  fancy-fete:
    build: .
    container_name: fancy-fete-app
    ports:
      - "3000:3000"
    environment:
      - TZ=Europe/Brussels
    volumes:
      - ./db.json:/app/db.json
      # MONTE TOUT LE DOSSIER PUBLIC (au lieu de juste plats.json)
      - ./public:/app/public
      # MONTE LE SERVEUR
      - ./server.js:/app/server.js
      # Partage l'horloge de Fedora
      - /etc/localtime:/etc/localtime:ro
    restart: always
